title: The Bog Standard
description: A blog for reviewing toilets and displaying them on a map.
baseurl: ""  # Adjust if your site is in a subdirectory
url: "theBogStandard.org"  # Replace with your GitHub Pages URL
markdown: kramdown
plugins:
  - jekyll-feed
collections:
  notes:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - toilet0.md